'theme: jekyll-theme-slate
title : Statistics Blog
description: Matteo Pernarella 1606685
github:
  owner_name: Matteo Pernarella
  is_project_page: false
  
markdown: kramdown
kramdown:
  input: GFM    
